[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jolin-io/KI2022-tutorial-universal-differential-equations/main?filepath=01%20introduction%20to%20julia.ipynb)

<a href="https://www.jolin.io" target="_blank" rel="noreferrer noopener">
<img src="https://www.jolin.io/assets/Jolin/Jolin-Banner-Website-v1.1-darkmode.webp">
</a>

# Introduction to <img height="60px" style='height:60px;display:inline;' alt="Julia" src="https://julialang.org/assets/infra/logo.svg">

Julia solves the two language problem of being both a high-level simple language like Python as well as super performant with speed of C.

This is a Juypter notebook which runs Julia as the kernel. You can actually interact with it, adapt code, and run code cells. You run cells and jump to the next by pressing SHIFT + ENTER. 

In [18]:
1 + 1

2

In [19]:
cos(pi)

-1.0

## Variables 
Julia was build for doing applied math and comes with a simple syntax. You can assign variables by plain `=` like in Python or R.

In [20]:
a = 3

3

👉 Let's do some calculations

In [21]:
# TODO calculate 2a + a²

Quite common in Julia is the use of greek symbols and some other cool utf-8 stuff. Typing backslash \ and then the latex name of something, and finish with pressing TAB, you can insert many symbols quite conveniently. Try it out!

In [22]:
θ = 1.34  # \theta
2θ

2.68

In [23]:
π # some special constants already exist in Julia

π = 3.1415926535897...

In [24]:
a² = a*a  # a\^2

9

## If/Else 
In Julia you have a multiline if/else block and the ternary question mark operator ``?``.

In [31]:
if a == 1
    println("1 a")
elseif a in (2,3,4,5)
    println("$a as")
else
    println("Don't know...")
end

3 as


In [29]:
a == 3 ? "three" : "other"

"three"

In addition you have short-cycling AND `&&`, and OR `||`. In both cases, the first argument has to be a boolean, however the last argument can be anything.

In [32]:
true && 1  # && evaluates and returns the second argument if the first is true

1

In [33]:
false && 1  # && otherwise returns false

false

In [34]:
returnvalue = false || println("Note that `nothing` is returned")  # || evaluates and returns the second argument if the first is false
returnvalue == nothing

Note that `nothing` is returned


true

In [35]:
true || error("this is not executed")  # || otherwise returns true

true

You see these in loops or functions commonly, where it is combined with `return`, `continue`, or `break`. 

## Functions

While variables are the synapsis, the brain of Julia are its functions. Really: If you understood functions in Julia, you are ready to work in Julia.

There are many functions available builtin, we already saw a couple of them.

In [36]:
isodd(3), iseven(a), a + a, +(a, a), 1 in (1,2), in(1, [1,2,3])

(true, false, 6, 6, true, true)

It is super simple to define your own functions

In [37]:
"""
    add2(a)
    
adds 2 to the given input and returns the result
"""
add2(a) = a + 2

add2

With the multiline string ("""...""") we just attached a documentation to our function. You can access it via ?, `@doc`, or by writing the open parentheses and pressing SHIFT+TAB

In [43]:
@doc add2

```
add2(a)
```

adds 2 to the given input and returns the result


In [ ]:
add2(  # try pressing SHIFT+TAB here

👉 Now lets actually run our function, if you haven't done so already

In [ ]:
# TODO add2 to 7, 99, 100

There is a second syntax to create functions which span multiple lines

In [ ]:
function add2(a, b)
    a′ = add2(a)  # a\prime = ...
    b′ = add2(b)
    return a′, b′ # the return statement is actually optional, the last statement in a block is automatically selected as the return value
end

In [ ]:
c, d = add2(1, 2)

Finally you have support for arbitrary number of positional and keyword arguments

In [44]:
args_kwargs(args...; kwargs...) = (args, kwargs)  # mind the semicolon ;
args_kwargs(1,true, :IAmASymbol, b=4, c="IAmAString")

((1, true, :IAmASymbol), Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:b, :c), Tuple{Int64, String}}}(:b => 4, :c => "IAmAString"))

The most fancy part about functions is that you can overload them for arbitrary number of arguments, as well as arbitrary argument types.

In [45]:
func(a::Int) = a + 2
func(a::AbstractFloat) = a/2
func(a::Rational) = a/11
func(a::Complex) = sqrt(a) 
func(a, b::String) = "$a, $b"

func (generic function with 5 methods)

In [46]:
func(1)

3

In [47]:
func(3.0)

1.5

In [48]:
func(33//4)  # you have full support for working with true rational numbers in Julia

3//4

In [49]:
func(-2 + 0im)

0.0 + 1.4142135623730951im

In [50]:
func(true, "it just works and compiles down to optimal code")

"true, it just works and compiles down to optimal code"

Welcome to the power of Julia!

## Exercise - Fibonacci, Memoize, and BenchmarkTools
👉 By now you have everything you need to define your own fibonacci function :) https://en.wikipedia.org/wiki/Fibonacci_number

In [ ]:
# TODO Implement fibonacci(n) returning the nth fibonacci number

This generates optimal code for small numbers of `n`, however gets quickly out of reach for larger `n` (for 45 it takes about 7 seconds for me). We can optimize the function by reusing already computed results. A quick trick to do so is to use the ``@memoize`` Macro from the ``Memoize`` package.

In [51]:
using Memoize

In [52]:
@memoize function fibonacci_mem(n)
    # TODO fill with your implementation
end

fibonacci_mem (generic function with 1 method)

With the help of the famous `@benchmark` macro from the `BenchmarkTools` package you can directly compare the time and memory footprint of the two functions.

In [53]:
using BenchmarkTools

In [ ]:
@benchmark fibonacci(30)

In [ ]:
@benchmark fibonacci_mem(30)

As you can see the memoization kicks in and we have about constant access time.

# Short excurse to Macros

Macros rewrite code. Simple as that. You can always inspect what a macro does using `@macroexpand` macro.

In [59]:
@show a;

a = 3


In [58]:
@macroexpand @show a

quote
    Base.println("a = ", Base.repr(begin
                #= show.jl:1047 =#
                local var"#63#value" = a
            end))
    var"#63#value"
end

In [56]:
@macroexpand @benchmark fibonacci(30)

quote
    #= /home/ssahm/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:392 =#
    local var"##291" = begin
                #= /home/ssahm/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:442 =#
                BenchmarkTools.generate_benchmark_definition(Main, Symbol[], Any[], Symbol[], (), $(Expr(:copyast, :($(QuoteNode(:(fibonacci(30))))))), $(Expr(:copyast, :($(QuoteNode(nothing))))), $(Expr(:copyast, :($(QuoteNode(nothing))))), BenchmarkTools.Parameters())
            end
    #= /home/ssahm/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:393 =#
    (BenchmarkTools).warmup(var"##291")
    #= /home/ssahm/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:394 =#
    (BenchmarkTools).tune!(var"##291")
    #= /home/ssahm/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:395 =#
    (BenchmarkTools).run(var"##291")
end

## Arrays

Arrays are the best supported DataType in Julia, it is multidimensional and highly optimized. You use it as both `list` and `numpy.array` in Python, i.e. no more switching between worlds.

In [ ]:
[1,2,3,4]  # create column vector with respective elements

In [ ]:
[1 2 3 4]  # horizontally concatinate elements separated by space

In [ ]:
[1
 2
 3
 4]  # vertically concatinate elements separated by newline

In [ ]:
[1; 2; 3; 4]  # vertically concatinate elements separated by semicolon

👉 Let's create a matrix

In [ ]:
# TODO create matrix with first row consisting of 1 & 2 and second row of 3 & 4

There are many common functions for dealing with Arrays, most importantly for construction

In [62]:
Array{String}(undef, (2,5))

2×5 Matrix{String}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

In [61]:
fill(5, (3,4))

3×4 Matrix{Int64}:
 5  5  5  5
 5  5  5  5
 5  5  5  5

You also have indexing support

In [84]:
array = [100, 200, 300]

3-element Vector{Int64}:
 100
 200
 300

👉 first index and last index 

In [68]:
# TODO get the first element

In [65]:
# TODO get the last element

A beautiful aspect of julia is that many many things are not at all hardcoded, but actually have generic implementations under the hood.

One of these is applying a function elementwise to an array, also called broadcasting.

In [85]:
add2.(array)  # mind the dot!! Try without dot

3-element Vector{Int64}:
 102
 202
 302

In [86]:
# the dot syntax translates to
broadcast(add2, array)

3-element Vector{Int64}:
 102
 202
 302

In [87]:
array .== 100  # try without dot

3-element BitVector:
 1
 0
 0

You can transpose an Array by using '

In [88]:
array .+ array'  # Can you understand what is happening here?

3×3 Matrix{Int64}:
 200  300  400
 300  400  500
 400  500  600

At last I want to highlight that unlike Numpy in Python, Julia's Arrays can really hold any type of data.

In [89]:
mycombine(a, b) = (a, b, [a + b])
mycombine.(array, array')

3×3 Matrix{Tuple{Int64, Int64, Vector{Int64}}}:
 (100, 100, [200])  (100, 200, [300])  (100, 300, [400])
 (200, 100, [300])  (200, 200, [400])  (200, 300, [500])
 (300, 100, [400])  (300, 200, [500])  (300, 300, [600])

Alternatively you can construct the same with a multi-dimensional for comprehension

In [90]:
[mycombine(x, y) for x in array, y in array]

3×3 Matrix{Tuple{Int64, Int64, Vector{Int64}}}:
 (100, 100, [200])  (100, 200, [300])  (100, 300, [400])
 (200, 100, [300])  (200, 200, [400])  (200, 300, [500])
 (300, 100, [400])  (300, 200, [500])  (300, 300, [600])

## Exercise - Fibonacci 2.0

Now you are already able to implement your own efficient version of `fibonacci_improved` which reuses intermediate results.

The exercise is not to reimplement memoize, concretely, the fibonacci call should not cache its final result, but only improve internal performance.

In [ ]:
# TODO implement fibonacci_improved

In [ ]:
@benchmark fibonacci_improved(50)

You can see that performance improved drastically, while now having a memory footprint on each call

## NamedTuples & Structs

In practice you often have a bunch of variables you need to handle at once. 
* In julia you of course can construct your own types for this, but they may be a bit clumsy at times.
* Luckily there is also a super simple to use alternative - named tuples - which you can use for fast development.

We already saw tuples and tuple destructing

In [75]:
x, y = (1,2)

(1, 2)

you can also give them names

In [76]:
namedtuple = (key=1, value=2)

(key = 1, value = 2)

In [77]:
namedtuple.key

1

This is one of the most useful tools for fast prototyping. There is even no performance penalty in using namedtuples, actually it is able to create optimal code.

In case you want to define your own types for a more stable interface between different parts of your code you can use `struct`.

In [78]:
struct MyType
    key::Int        # always specify the types by prepending ::
    value::String
end

In [ ]:
MyType(3, "hi").value  # TODO construct MyType with other arguments

If you want flexible types, best way is to parameterize your types

In [79]:
struct MyType2{Key, Value}
    key::Key
    value::Value
end

In [80]:
MyType2("yeah", true)  # you see the types are automatically inferred

MyType2{String, Bool}("yeah", true)

There is also the alternative of not specifying types at all
```julia
struct MyType3
    key
    value
end
```
Which is equivalent to specifying
```julia
struct MyType3
    key::Any
    value::Any
end
```
Very important to know is that this leads to pour type inference and hence pourer performance. If you run ``MyType3(1, "value").key`` julia does not know any longer that the key is actually of type Int,  this was forgotten when wrapped into the MyType3. Hence not much code optimization can be done.

Always prefer to parameterize your types, as it is not much work and gives you optimal performance.

In [81]:
func(a::MyType2) = "$(a.key): $(a.value)"

func (generic function with 6 methods)

Yes, you can overload functions for your own types - actually any function, also those already defined by other packages including Julia builtin functions.

In [82]:
func(MyType2(42, "Multiple Dispatch this is called, and it is the answer to almost everything"))

"42: Multiple Dispatch this is called, and it is the answer to almost everything"

### At last the loops

In [83]:
for i in 1:4
    println(i)
end

1
2
3
4


Behind the scene
```julia
for item in iterable   # or  "for item = iter"
    # body
end
```
is translated to
```julia
next = iterate(iterable)
while next !== nothing
    (item, state) = next
    # body
    next = iterate(iterable, state)
end
```

In [96]:
iterable = 1:4
next = iterate(iterable)
while next !== nothing
    (item, state) = next
    print(item, " ")
    next = iterate(iterable, state)
end

1 2 3 4 

The state is an implementation detail of each iterator. The separate state makes julia's loops as fast as loops.


In [94]:
for i ∈ eachindex(array)  # this works also for arrays with non-standard index
    @show i
    @show array[i]
end

i = 1
array[i] = 100
i = 2
array[i] = 200
i = 3
array[i] = 300


In [99]:
for a ∈ array
    @show a
end

a = 100
a = 200
a = 300


In [101]:
for (i, a) ∈ enumerate(array)
    @show i a
end

i = 1
a = 100
i = 2
a = 200
i = 3
a = 300


You can easily inspect the source code of a given function.

👉 try understand how enumerate works in Julia

In [104]:
@which iterate(enumerate(array))

iterate(e::Base.Iterators.Enumerate) in Base.Iterators at iterators.jl:157

# That was the introduction to Julia - Thank you for participating 🙂

Next topic is how to do deep-learning in Julia: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jolin-io/KI2022-tutorial-universal-differential-equations/main?filepath=02%20introduction%20to%20deep%20learning%20in%20julia.ipynb)